-- 010: Create mayfly_app role without BYPASSRLS
--
-- IMPORTANT: This migration CANNOT be run via scripts/run-migration.ts
-- because the DO block contains semicolons. Run it manually in the Supabase SQL Editor.
--
-- This role respects RLS policies, enforcing tenant isolation at the DB level.
-- The postgres role (BYPASSRLS) is kept for migrations, admin ops, and bootstrap.
--
-- After running this migration:
-- 1. Set a secure password for the role in Supabase SQL Editor
-- 2. Build a connection string: postgresql://mayfly_app:<password>@<host>:5432/postgres
-- 3. Update DATABASE_URL in .env.local to use the mayfly_app role
-- 4. Keep DIRECT_URL pointing to the postgres role for migrations
--
-- Run the following SQL in the Supabase SQL Editor:
--
-- DO $$
-- BEGIN
--   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'mayfly_app') THEN
--     CREATE ROLE mayfly_app LOGIN PASSWORD 'your-secure-password-here'
--       NOSUPERUSER NOCREATEDB NOCREATEROLE;
--   END IF;
-- END
-- $$;
--
-- GRANT USAGE ON SCHEMA public TO mayfly_app;
-- GRANT USAGE ON SCHEMA auth TO mayfly_app;
-- GRANT EXECUTE ON FUNCTION auth.uid() TO mayfly_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON users TO mayfly_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON projects TO mayfly_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON chat_conversations TO mayfly_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON chat_messages TO mayfly_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON user_status_history TO mayfly_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON user_devices TO mayfly_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON user_sessions TO mayfly_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON meetings TO mayfly_app;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public
--   GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mayfly_app;
